<a href="https://colab.research.google.com/github/Rajathshivraj/ML/blob/main/Completenumpytutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY-numericalpython
advantages-
1.allows several math operations
2.faster operations

In [ ]:
import numpy as np

list vs numpy time taken

In [ ]:
from time import process_time

time taken by list

In [ ]:
python_list=[i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.0006156649999997654


time taken by numpy array

In [ ]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)

0.00016279399999952204


numpy arrays

In [ ]:
#list
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# creating a 1 dim array
a = np.array([1,2,4,4,5])
print(a)


[1 2 4 4 5]


In [ ]:
a.shape

(5,)

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


initial placeholders in numpy arrays

In [ ]:
import numpy as np
#create a numpy arrays of zero
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#create a numpy of arrays of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#arrays of particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
a = np.full((5,4),0)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
#create a identity matrix
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#create numpy array with random values
b = np.random.random((3,4))
print(b)
#all values will be btw 0 and 1

[[0.3748661  0.54013411 0.81703647 0.37591886]
 [0.51801242 0.66681755 0.57735593 0.26466547]
 [0.1159046  0.13988741 0.12317616 0.00844731]]


In [ ]:
#random integer value
c = np.random.randint(10,100,(3,5))
print(c)

[[40 98 15 72 16]
 [56 33 12 31 11]
 [50 21 96 36 74]]


In [ ]:
#array of evenly spaced values specifying the values required
import numpy as np
d = np.linspace(10,30,4)
print(d)

[10.         16.66666667 23.33333333 30.        ]


In [ ]:
# array of evenly spaced values specifying the next step
e = np.arange(10,30,5)
print(e)
#here print the value of steps

[10 15 20 25]


In [ ]:
#convert a list to a numpy array
list1 = [10,20,40]
np_array=np.asarray(list1)
print(np_array)
print(type(list1))
print(type(np_array))

[10 20 40]
<class 'list'>
<class 'numpy.ndarray'>


ANALYSING A NUMPY ARRAY

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[54 12 22 15 58]
 [23 36 23 63 88]
 [31 44 75 73 71]
 [42 24 67 58 42]
 [78 30 44 30 30]]


In [ ]:
print(c.shape)

(5, 5)


In [ ]:
print(c.ndim)

2


In [ ]:
print(c.size)

25


In [ ]:
print(c.dtype)

int64


Mathemeatical operations on a np array

In [ ]:
list1 =[1,2,3,4,5]
list2 =[6,7,8,9,10]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[4 9 1]
 [4 8 5]
 [5 6 1]]
[[18 13 17]
 [19 18 12]
 [18 10 10]]


In [ ]:
print(a+b)

[[22 22 18]
 [23 26 17]
 [23 16 11]]


In [ ]:
print(a-b)
print(a+b)
print(a*b)
print(a/b)


[[-14  -4 -16]
 [-15 -10  -7]
 [-13  -4  -9]]
[[22 22 18]
 [23 26 17]
 [23 16 11]]
[[ 72 117  17]
 [ 76 144  60]
 [ 90  60  10]]
[[0.22222222 0.69230769 0.05882353]
 [0.21052632 0.44444444 0.41666667]
 [0.27777778 0.6        0.1       ]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[22 22 18]
 [23 26 17]
 [23 16 11]]
[[-14  -4 -16]
 [-15 -10  -7]
 [-13  -4  -9]]
[[ 72 117  17]
 [ 76 144  60]
 [ 90  60  10]]
[[0.22222222 0.69230769 0.05882353]
 [0.21052632 0.44444444 0.41666667]
 [0.27777778 0.6        0.1       ]]


ARRAY MANIPULATION

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[6 6 7]
 [2 3 3]]
(2, 3)


In [ ]:
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[6 2]
 [6 3]
 [7 3]]
(3, 2)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[6 2]
 [6 3]
 [7 3]]
(3, 2)


In [ ]:
#reshaping array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[7 6 1]
 [4 6 1]]
(2, 3)


In [ ]:
b = a.reshape(3, 2)
print(b)
print(b.shape)

[[7 6]
 [1 4]
 [6 1]]
(3, 2)
